import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Index.module.scss'
import back1 from "../public/8a8375ab7908384e1fd6efe408284203.svg"
import back2 from "../public/c40c84ca18d84633a9d86b4046a91437.svg"
import Content from '../components/Home/Content'

export default function Home() {
  return (
    <>
      <Head>
        <title>DiscordClone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Image 
          src={back1}
          alt="backimage"
          className={styles.back1}
        />
        <Image 
          src={back2}
          alt="backimage"
          className={styles.back2}
        />
        <Content/>

      </main>
    </>
  )
}
